webserver:
  build: images/webserver
  links:
    - buildFront
  ports:
    - "80:80"
  volumes_from:
    - frontenddata

buildFront:
    build: images/build


frontenddata:
  image: busybox
  volumes:
    - "sites/frontend.conf:/etc/nginx/sites-enabled/frontend.conf"
    - "dist/:/var/www/frontend/"

