webserver:
  build: images/webserver
  links:
    - frontendbuild
  ports:
    - "80:80"
  volumes_from:
    - frontenddata

frontendbuild:
    build: .



frontenddata:
  image: busybox
  volumes:
    - "sites/frontend.conf:/etc/nginx/sites-enabled/frontend.conf"
    - "dist/:/var/www/frontend/"

